language: ruby
script:
  - bundle exec rake
  - cd doc/example && bundle install --jobs=3 --retry=3 --deployment && bundle exec rspec
rvm:
  - 2.0.0-p247
  - 2.1.1
  - 2.0.0
gemfile:
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-4.1.gemfile
