language: ruby
cache: bundler
before_install: "cd $TEST_DIR"
install: "bundle install --jobs=3 --retry=3"
env:
  - TEST_DIR=.
  - TEST_DIR=doc/example
rvm:
  - 2.1.1
  - 2.0.0
gemfile:
  - $TEST_DIR/gemfiles/rails-4.0.gemfile
  - $TEST_DIR/gemfiles/rails-4.1.gemfile
