language: ruby
cache: bundler
install: "cd $TEST_DIR && bundle install --jobs=3 --retry=3"
script:  "cd $TEST_DIR && bundle exec rake"
env:
  - TEST_DIR=.
  - TEST_DIR=doc/example
rvm:
  - 2.1.1
  - 2.0.0
gemfile:
  - $TEST_DIR/gemfiles/rails-4.0.gemfile
  - $TEST_DIR/gemfiles/rails-4.1.gemfile
